/**
 * Generates src/data/fbs.ts — the FBS team identity list (ids, colours,
 * stadiums, coordinates, conference, latest Elo) — from the CollegeFootballData
 * team-info parquet and schedule files mirrored in sportsdataverse/cfbfastR-data.
 *
 *   npm run data:gen-teams
 *
 * Re-run each off-season when conference membership changes. Everything that
 * is a judgement call (coverage family, base front, stadium noise bumps,
 * rivalries) lives in src/data/curated.ts, not here.
 */
import fs from 'node:fs';
import path from 'node:path';
import { download, readCsv } from '../pipeline/lib/fetch';
import { readParquetObjects, pnum, pstr, pbool } from '../pipeline/lib/parquet';
import { num } from '../pipeline/lib/util';

const RAW = 'https://raw.githubusercontent.com/sportsdataverse/cfbfastR-data/main';

export const slugify = (s: string) =>
  s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/&/g, '').replace(/'/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

/** CFBD disambiguates duplicate venue names with a parenthetical city — the app shows the city separately. */
const cleanVenue = (v: string) => v.replace(/\s*\([^)]*\)\s*$/, '').trim();

async function main() {
  const season = Number(process.argv[2] ?? new Date().getFullYear());
  const infoFile = (await download(`${RAW}/team_info/parquet/cfb_team_info_${season}.parquet`, `CFBD team info ${season}`, { ttlMinutes: 1440, optional: true }))
    ?? (await download(`${RAW}/team_info/parquet/cfb_team_info_${season - 1}.parquet`, `CFBD team info ${season - 1}`, { ttlMinutes: 1440 }))!;
  const rows = await readParquetObjects(infoFile);
  const fbs = rows.filter((r) => pstr(r.classification) === 'fbs');

  // Latest Elo per team from the most recent schedule file that has one.
  const elo = new Map<number, number>();
  for (const yr of [season, season - 1]) {
    const f = await download(`${RAW}/schedules/csv/cfb_schedules_${yr}.csv`, `CFBD schedule ${yr}`, { ttlMinutes: 60, optional: true });
    if (!f) continue;
    const games = (await readCsv(f)).sort((a, b) => a.start_date.localeCompare(b.start_date));
    for (const g of games) {
      for (const side of ['home', 'away'] as const) {
        const id = num(g[`${side}_id`]);
        const post = num(g[`${side}_postgame_elo`]);
        const pre = num(g[`${side}_pregame_elo`]);
        const v = Number.isFinite(post) ? post : pre;
        if (Number.isFinite(v)) elo.set(id, v);
      }
    }
    if (elo.size > 100) break;
  }

  const seen = new Set<string>();
  const teams = fbs
    .map((r) => {
      const school = pstr(r.school);
      let id = slugify(school);
      if (seen.has(id)) id = `${id}-${pnum(r.team_id)}`;
      seen.add(id);
      const elevM = pnum(r.elevation);
      return {
        id,
        espnId: pnum(r.team_id),
        abbr: pstr(r.abbreviation) || school.slice(0, 4).toUpperCase(),
        school,
        mascot: pstr(r.mascot),
        conference: pstr(r.conference),
        colors: [pstr(r.color) || '#333333', pstr(r.alt_color) || '#ffffff'],
        stadium: {
          name: cleanVenue(pstr(r.venue_name)) || `${school} Stadium`,
          city: [pstr(r.city), pstr(r.state)].filter(Boolean).join(', '),
          dome: pbool(r.dome),
          capacity: Number.isFinite(pnum(r.capacity)) ? pnum(r.capacity) : 40000,
          altitudeFt: Number.isFinite(elevM) ? Math.round(elevM * 3.281) : 500,
          lat: pnum(r.latitude),
          lng: pnum(r.longitude),
        },
        elo: elo.get(pnum(r.team_id)) ?? null,
        // ESPN's CDN serves every FBS logo by the same numeric id and is the one the NFL sibling app already relies on.
        logoUrl: `https://a.espncdn.com/i/teamlogos/ncaa/500/${pnum(r.team_id)}.png`,
      };
    })
    .sort((a, b) => a.conference.localeCompare(b.conference) || a.school.localeCompare(b.school));

  const missing = teams.filter((t) => !Number.isFinite(t.stadium.lat));
  if (missing.length) console.warn('teams without coordinates:', missing.map((t) => t.school).join(', '));

  const out = `/**
 * GENERATED by scripts/gen-teams.ts from CollegeFootballData team info
 * (${season}) and schedule Elo — do not edit by hand. Curated judgement calls
 * (coverage, front, scheme, noise, rivalries) live in ./curated.ts.
 */
export interface FbsTeamIdentity {
  id: string; espnId: number; abbr: string; school: string; mascot: string; conference: string;
  colors: [string, string];
  stadium: { name: string; city: string; dome: boolean; capacity: number; altitudeFt: number; lat: number; lng: number };
  /** Latest Elo from the schedule feed at generation time (null if unknown). */
  elo: number | null;
  logoUrl?: string;
}

export const FBS_SEASON = ${season};

export const FBS_TEAMS: FbsTeamIdentity[] = ${JSON.stringify(teams, null, 1).replace(/"([a-zA-Z_][a-zA-Z0-9_]*)":/g, '$1:')};
`;
  const dest = path.resolve(__dirname, '../src/data/fbs.ts');
  fs.writeFileSync(dest, out);
  console.log(`wrote ${path.relative(process.cwd(), dest)} · ${teams.length} FBS teams · Elo for ${teams.filter((t) => t.elo !== null).length}`);
}

main().catch((e) => { console.error(e); process.exitCode = 1; });
